#define M(m,n,z) _(ij=en(m*n-n,n,a);r(mz(m,tn(ta,j)-j+m*n),z))
#include"b.c"//+-*%&|<>=~ .! @? #_ ^,
_Z(m6,i(n/4,Ez[4]={};EX=x;h(m,i(4,zi+=A[h]*X[i])X+=n)i(4,R_=zi)x+=4)i(n%4,Ez={};EX=x++;h(m,z+=A[h]**X;X+=n)R_=z),im,in,ER,eA,e6*x)F(mv,R(tx,ma,eR=sr;i(ma,R_=sE(a2+i*nx,x))))
F(vm,ik=kx;R(tx,k,m6(mx,n4(k),r2,a2,x2)))F(mm,ik=kx;M(ma,k,i(ma,m6(mx,n4(k),r2+k*i,a2+mx*i,x2))))F(at,Qn(ka!=mn)_a(_x(ma|mx?(ma?mx?mm:mv:vm)(a,x):te(sE(aE,x)))))
_F(S,Qn(ma!=mx|na!=nx)_a(_x(R(tx,kx,VR=sr;in=nr/16;i(n/4,Ez[4]={};EA=aE+4*i;EX=xE+4*i;i(mx,i(4,zi+=AZ*X_)A+=n-4;X+=n-4)i(4,R_=zi))))))
G(VV,Qn(ka!=mn)Qz(i&2!=i)it=ma;if(t){Uu=a;a=x;x=u;}ik=kx;_a(_x(M(mx,k,h(mx,VR=r2+h*k;VX=x2+h*k;$(t,EA=a2;$(i,J(4*k,R_=AZ*Ex))J(4*k,R_=AZ+Ex))$(i,J(4*k,R_=ae[h]*Ex))J(4*k,R_=ae[h]+Ex))))))
F(CC,im=ma?:na;_a(R(0,m+mn,U*R=sr;j(nr,R_=j<m?a_(j,a):a_(j-m,x)))))inx(dz,_x(mz(mx,r(tn(tx,i)-i+n,ds(Nx,sr,sx)))))
F(_C,a=aa?v(a):a;x=ax?v(x):x;in=en(na,nx,x);_x(!ta|ta!=tx|ka*!!ma!=kx*!!mx?CC(a,x):mz(ma+mx,r(hn(ta,n)>ra>>59?dz(n,na+nx,a):a+nx,ds(Nx,sr+Na,sx)))))
g(iZ,x) //_x(r(mtn(mx,tx,nx/i),))) eR=sr;eX=sx;h(mx,i(i,R_=2.3))))) //se(kx/i,X))X+=kx/i)))) //ERZ 48\ZS''6^'
g(T,ax?4>i?t(i,ix):te(ex):t_(--i>tx?T(i,x):x))f(T4,4>tx?T(4,x):x)f(_v,ax?x:_x(a_(0,x)))G(E4,ax?_v(E4(i,a,v(x))):a&&aa&&2==i?iZ(a,x):eE(i,a?T4(a):a,T4(x)))
G(Q4,P(a,Qr(aa)(ma&&mx?S:at)(T4(a),P0(x)))_x(te(se(nx,sx)/nx)))ZU e1(ii,U);f(s,!tx|mx?e1(11,x):_x(mz(2>nx?0:*x2,nz(pi(x),te(1)))))f(n_,ax?nz(x,0):4==tx?x:s(x))f(ty,ti(ax?tx:_x(tx)))
#define A(G,I,E) 4>i?V(4>tx?$3(i,I+Ix,I-Ix,(I)*Ix):$4(i,E+Ex,E-Ex,(E)*Ex,(E)/Ex)):6>i?V(3>tx?(5>i?LG:MG)(G,*X):(5>i?LI:MI)(I,*X)):3>tx?_V(1,U,bg($3(i-6,G<*X,G>*X,G==*X))):_V(1,i1,bi($3(i-6,I<*X,I>*X,I==*X)))
G(av,A(ga-z0,ia-z2,ea-ze))_U(Av,A(AZ,(i6)AZ,(e6)AZ),ii,VA,Ux)G(vv,_a(Av(i,sa,x)))g(pe,P(1==tx,pB(i,x))Ua=i?*xU:0;Uc=b(1<<bx);x=i--?Av(i^2>i-6,sx-(1<<bx-3),x):_x(ln(-1,nx,x));*xU=c&a|~c&*xU;x)
G(a9,ij=ia;4>i&3<tx?_v(av(i,a,v(x))):6>i?t(tx,$6(i,j+ix,j-ix,j*ix,0,l(j,ix),m(j,ix))):tb($3(i-6,j<ix,j>ix,j==ix)))f(y,4>tx?ti(-ix):te(-ex))g(tt,m(3>i?3:4>i?4:0,tx))
G(Z,P(!tx,H(Z(i,a,a_(j,x))))it=m(ta,tt(i,x));a=t>ta?T(t,a):a;x=t>tx?T(t,x):x;aa<ax?av(i-(1==i|3==i)^2>i-6,1==i?y(x):3==i?te(1/ex):x,a):(aa?ax?a9:av:!ma^!mx?VV:vv)(i,a,x))
_g(z,P(!tx,H(z(i,a_(j,x))))it=tt(i,x);x=t>tx?T(t,x):x;$5(i,0,ax?y(x):4>tx?V(-Ix):V(-Ex),(ax?a9:VV)(2,r_(x),x),E4(3,0,x),10>i?tx?tb(!jx):V(~X_):ax?ti(ex):_t(x)))
G(MD,P(!i--|3<m(ta,tx),Z(2,i?a:te(1/ea),x))in=a;P(ax,ti(i?ix%n:ix/n))Qn(n-1>>16)im=(n+65535)/n;i?V(m*Ix>>16):V(i6 a=Ix;a-n*(m*a>>16)))G(P4,!a&3>i?o3(i,x):Q4(i,a,T4(x)))
F(A_,P(ma,M(nx,ka,ik=ka<<ba-3;i(nx,ds(k,sr+k*i,sa+k*x2[i]))))i2*X=x2;$4(ta,H(r_(aU[X_])),0,H2(sa[X_]),r(uz(x),i(nx,r2[i]=a2[X_]))))f(_n,ti(ax?1:_x(mn)))
_F(_A,Qr(ma)Qz(100<nx)Qt(ta!=tx|1<ta-2)H3(iz(3>tx?sx[j]:x2[j],a)))G(AA,it=i?ta:3;aa?MD(i,a,x):4==tx&!ax?at(a,x):_a(ax?i?ti(iz(x,a)):a_(x,a):(i?_A:A_)(a,t>tx?T(t,x):x)))
G(NN,Qr(!aa)in=a;P(ax,nz(n,x))im=mn;Qn(n>m)n>>31^i?(n+=!i*m,_x(ln(n,m-n,x))):x-(i?-n:m-n))F(C_,Qr(!aa|ax|mx)Qt(!tx)mz(ia>>31?nx/-ia:ia,x))
Z0 b[1<<23];_f(_E,V(b(23)&(i6)(1+Ex)))_f(E_,V((e6)(127<<23|Ix)-1))g(uf,Qz(!i|4!=tx)x=_E(x);x)
f(uq,ax?4>tx?nz(x,2):te(ex/0x1p64*PQ()[0]):uf(0,x))f(fq,uf(1,x))g(of,QR Qt(5!=bx)0)f(sq,ax?nz(x,1):of(0,x))f(_o,of(1,x))f(o_,of(2,x))f(ff,0)g(ie,Qz(1!=i)of(0,x))
f(dt,x)g(po,P(!i--,a_(nx-1,x))P(17==i,Qz(!tx)mz(0,x))P(2==i,Qt(3!=tx)_x(t(tx,pi(x))))Qz(!!i&1<i-4)o3(i?i-4:2,x))g(ps,Qz(!i--)Qz(mx)P(2>tx,sB(i,x))Qz(!!i&1<i-4)s3(i?i-4:2,x))g(io,0)g(is,0)
Zf(f,ff,rr,o_,_o,fq,0,dt,n_,_v,uq,_n,0,sq,v,q0)_i(q,4>i|9==i|15==i)_g(e1,H(Ua=a_(j,x);q(i)?z(i,a):f[i-4](a)))Zg(g,ie,pe,io,po,is,ps)G(O3,QR Qz(!aa)!i&9>a-10?e1(a,x):g[2*i|pa](a,x))
G_(k,k_();!i--?a?(U)sa:x?r_(x):ti(W):19>i?a?10>i?Z(i,a,x):16>i?(14>i?AA:NN)(1&i,a,x):$3(i-16,C_,_C,Q0)(a,x):!i?ty(x):q(i)?z(i,x):f[i-4](x):25>i?P4(i-19,a,x):28>i?E4(i-25,a,x):O3(i-28,a,x))
